version: "3"
services:
  app:
    container_name: user-crud
    restart: always
    build:
      context: .
      args:
        NODE_ENV: development
    command: npm run start
    ports:
      - 4000:4000
    volumes:
      - .:/srv/
      - /srv/node_modules
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb-user-crud
    image: mongo
    restart: always
    ports:
      - 27017:27017